
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file: ./docker/pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3000:3000"
    env_file: ./docker/backend.env

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "8080:8080"
    env_file: ./docker/frontend.env

volumes:
  postgres_data:
  pgadmin_data:
